package download

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	tfjson "github.com/hashicorp/terraform-json"

	"github.com/redtenant/tfmigrate/pkg/generator"
	"github.com/redtenant/tfmigrate/pkg/state"
	"github.com/redtenant/tfmigrate/pkg/upload"
)

// mockUploader implements upload.BlobUploader for testing.
type mockUploader struct {
	blobs map[string][]byte // blobName -> content
}

func newMockUploader() *mockUploader {
	return &mockUploader{blobs: make(map[string][]byte)}
}

func (m *mockUploader) Upload(_ context.Context, blobName string, content []byte) error {
	m.blobs[blobName] = append([]byte{}, content...)
	return nil
}

func (m *mockUploader) ListBlobs(_ context.Context, prefix string) ([]string, error) {
	var names []string
	for name := range m.blobs {
		if len(name) >= len(prefix) && name[:len(prefix)] == prefix {
			names = append(names, name)
		}
	}
	return names, nil
}

func (m *mockUploader) DeleteBlob(_ context.Context, blobName string) error {
	delete(m.blobs, blobName)
	return nil
}

func (m *mockUploader) DownloadBlob(_ context.Context, blobName string) ([]byte, error) {
	data, ok := m.blobs[blobName]
	if !ok {
		return nil, fmt.Errorf("blob %q not found", blobName)
	}
	return append([]byte{}, data...), nil
}

// mockStateReader implements state.StateReader for testing.
type mockStateReader struct {
	states map[string]*tfjson.State
}

func newMockStateReader(states map[string]*tfjson.State) *mockStateReader {
	return &mockStateReader{states: states}
}

func (m *mockStateReader) ReadState(_ context.Context, layerPath string) (*tfjson.State, error) {
	s, ok := m.states[layerPath]
	if !ok {
		return &tfjson.State{}, nil
	}
	return s, nil
}

// makeState creates a tfjson.State with resources at the given addresses.
func makeState(addresses ...string) *tfjson.State {
	var resources []*tfjson.StateResource
	for _, addr := range addresses {
		resources = append(resources, &tfjson.StateResource{
			Address: addr,
			Type:    "test_resource",
			Name:    addr,
			Mode:    tfjson.ManagedResourceMode,
		})
	}
	return &tfjson.State{
		Values: &tfjson.StateValues{
			RootModule: &tfjson.StateModule{
				Resources: resources,
			},
		},
	}
}

// makeMigrationContent creates a .tf file content with embedded metadata.
func makeMigrationContent(meta *generator.MigrationMetadata) string {
	metaComment := generator.RenderMetadataComment(meta)
	return "# Generated by tfmigrate - do not edit manually\n" + metaComment + "\n# test block\nremoved {\n  from = test_resource.example\n}\n"
}

func TestDownloadNoConditions(t *testing.T) {
	mock := newMockUploader()
	content := makeMigrationContent(&generator.MigrationMetadata{
		Resources: []string{"test_resource.example"},
	})
	mock.blobs["migrations/migration.001_test.abcd1234.tf"] = []byte(content)

	dir := t.TempDir()
	// Write a backend.tf so DiscoverBackendConfig works
	writeBackendTF(t, dir)

	dl := NewDownloader(nil, nil, WithUploaderFactory(func(sa, cn string, _ azcore.TokenCredential) (upload.BlobUploader, error) {
		return mock, nil
	}))

	files, err := dl.Download(context.Background(), dir)
	if err != nil {
		t.Fatalf("Download error: %v", err)
	}

	if len(files) != 1 {
		t.Fatalf("expected 1 file written, got %d", len(files))
	}

	// Verify file was written
	outPath := filepath.Join(dir, "migration.001_test.abcd1234.tf")
	if _, err := os.Stat(outPath); os.IsNotExist(err) {
		t.Errorf("expected file %q to exist", outPath)
	}
}

func TestDownloadConditionMet(t *testing.T) {
	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesExist: []generator.MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"test_resource.existing"}},
			},
		},
		Resources: []string{"test_resource.existing"},
	}

	mock := newMockUploader()
	mock.blobs["migrations/migration.002_move.ef567890.tf"] = []byte(makeMigrationContent(meta))

	dir := t.TempDir()
	writeBackendTF(t, dir)

	// The downloader needs a state reader that returns the resource
	// We'll test this by overriding the condition evaluation through the full path
	// Since evaluateConditions uses a lazy state reader getter, we need to
	// ensure tofu is available or bypass the real state reader.
	// For unit testing, we test evaluateConditions directly below.

	dl := NewDownloader(nil, nil, WithUploaderFactory(func(sa, cn string, _ azcore.TokenCredential) (upload.BlobUploader, error) {
		return mock, nil
	}))

	// For this test, we test that the file is not written when tofu isn't available
	// (conditions can't be evaluated). The more detailed condition tests are below.
	_, err := dl.Download(context.Background(), dir)
	// This may fail because tofu isn't available in test env; that's expected.
	// The important thing is it doesn't panic.
	_ = err
}

func TestEvaluateConditionsResourcesExist(t *testing.T) {
	dl := &Downloader{}
	ctx := context.Background()

	stateWithResource := makeState("test_resource.example")
	reader := newMockStateReader(map[string]*tfjson.State{
		"/test/layer": stateWithResource,
	})

	getReader := func() (state.StateReader, error) {
		return reader, nil
	}

	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesExist: []generator.MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"test_resource.example"}},
			},
		},
	}

	result, err := dl.evaluateConditions(ctx, meta, getReader, "/test/layer")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result {
		t.Error("expected conditions to be met")
	}
}

func TestEvaluateConditionsResourcesExistFails(t *testing.T) {
	dl := &Downloader{}
	ctx := context.Background()

	emptyState := makeState() // no resources
	reader := newMockStateReader(map[string]*tfjson.State{
		"/test/layer": emptyState,
	})

	getReader := func() (state.StateReader, error) {
		return reader, nil
	}

	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesExist: []generator.MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"test_resource.missing"}},
			},
		},
	}

	result, err := dl.evaluateConditions(ctx, meta, getReader, "/test/layer")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result {
		t.Error("expected conditions to NOT be met")
	}
}

func TestEvaluateConditionsResourcesNotExist(t *testing.T) {
	dl := &Downloader{}
	ctx := context.Background()

	emptyState := makeState()
	reader := newMockStateReader(map[string]*tfjson.State{
		"/test/layer": emptyState,
	})

	getReader := func() (state.StateReader, error) {
		return reader, nil
	}

	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesNotExist: []generator.MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"test_resource.missing"}},
			},
		},
	}

	result, err := dl.evaluateConditions(ctx, meta, getReader, "/test/layer")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result {
		t.Error("expected conditions to be met (resource doesn't exist)")
	}
}

func TestEvaluateConditionsResourcesNotExistFails(t *testing.T) {
	dl := &Downloader{}
	ctx := context.Background()

	stateWithResource := makeState("test_resource.existing")
	reader := newMockStateReader(map[string]*tfjson.State{
		"/test/layer": stateWithResource,
	})

	getReader := func() (state.StateReader, error) {
		return reader, nil
	}

	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesNotExist: []generator.MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"test_resource.existing"}},
			},
		},
	}

	result, err := dl.evaluateConditions(ctx, meta, getReader, "/test/layer")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result {
		t.Error("expected conditions to NOT be met (resource exists)")
	}
}

func TestEvaluateConditionsCrossLayerWarning(t *testing.T) {
	dl := &Downloader{}
	ctx := context.Background()

	getReader := func() (state.StateReader, error) {
		return newMockStateReader(nil), nil
	}

	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesExist: []generator.MetadataResourceCheck{
				{Layer: "./other/layer", Addresses: []string{"test_resource.cross"}},
			},
		},
	}

	// Cross-layer conditions should be treated as met (with warning)
	result, err := dl.evaluateConditions(ctx, meta, getReader, "/test/layer")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result {
		t.Error("expected cross-layer condition to be treated as met")
	}
}

func TestEvaluateConditionsNil(t *testing.T) {
	dl := &Downloader{}
	ctx := context.Background()

	getReader := func() (state.StateReader, error) {
		return nil, nil
	}

	meta := &generator.MigrationMetadata{
		Conditions: nil,
	}

	result, err := dl.evaluateConditions(ctx, meta, getReader, "/test/layer")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result {
		t.Error("expected nil conditions to pass")
	}
}

func TestDownloadDryRun(t *testing.T) {
	mock := newMockUploader()
	content := makeMigrationContent(&generator.MigrationMetadata{
		Resources: []string{"test_resource.example"},
	})
	mock.blobs["migrations/migration.001_test.abcd1234.tf"] = []byte(content)

	dir := t.TempDir()
	writeBackendTF(t, dir)

	dl := NewDownloader(nil, nil, WithDryRun(true), WithUploaderFactory(func(sa, cn string, _ azcore.TokenCredential) (upload.BlobUploader, error) {
		return mock, nil
	}))

	files, err := dl.Download(context.Background(), dir)
	if err != nil {
		t.Fatalf("Download error: %v", err)
	}

	if len(files) != 1 {
		t.Fatalf("expected 1 file in dry-run, got %d", len(files))
	}

	// File should NOT be written in dry-run mode
	outPath := filepath.Join(dir, "migration.001_test.abcd1234.tf")
	if _, err := os.Stat(outPath); !os.IsNotExist(err) {
		t.Error("file should not exist in dry-run mode")
	}
}

func TestDownloadNoMigrations(t *testing.T) {
	mock := newMockUploader()

	dir := t.TempDir()
	writeBackendTF(t, dir)

	dl := NewDownloader(nil, nil, WithUploaderFactory(func(sa, cn string, _ azcore.TokenCredential) (upload.BlobUploader, error) {
		return mock, nil
	}))

	files, err := dl.Download(context.Background(), dir)
	if err != nil {
		t.Fatalf("Download error: %v", err)
	}

	if len(files) != 0 {
		t.Errorf("expected 0 files, got %d", len(files))
	}
}

// writeBackendTF writes a minimal backend.tf to the directory for DiscoverBackendConfig.
func writeBackendTF(t *testing.T, dir string) {
	t.Helper()
	err := os.WriteFile(filepath.Join(dir, "backend.tf"), []byte(`
terraform {
  backend "azurerm" {
    storage_account_name = "testacct"
    container_name       = "testcontainer"
  }
}
`), 0o644)
	if err != nil {
		t.Fatal(err)
	}
}
