package download

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	tfjson "github.com/hashicorp/terraform-json"

	"github.com/terraprovider/statebridge/pkg/generator"
	"github.com/terraprovider/statebridge/pkg/upload"
)

// mockUploader implements upload.BlobUploader for testing.
type mockUploader struct {
	blobs map[string][]byte // blobName -> content
}

func newMockUploader() *mockUploader {
	return &mockUploader{blobs: make(map[string][]byte)}
}

func (m *mockUploader) Upload(_ context.Context, blobName string, content []byte) error {
	m.blobs[blobName] = append([]byte{}, content...)
	return nil
}

func (m *mockUploader) ListBlobs(_ context.Context, prefix string) ([]string, error) {
	var names []string
	for name := range m.blobs {
		if len(name) >= len(prefix) && name[:len(prefix)] == prefix {
			names = append(names, name)
		}
	}
	return names, nil
}

func (m *mockUploader) DeleteBlob(_ context.Context, blobName string) error {
	delete(m.blobs, blobName)
	return nil
}

func (m *mockUploader) DownloadBlob(_ context.Context, blobName string) ([]byte, error) {
	data, ok := m.blobs[blobName]
	if !ok {
		return nil, fmt.Errorf("blob %q not found", blobName)
	}
	return append([]byte{}, data...), nil
}

// mockStateReader implements state.StateReader for testing.
type mockStateReader struct {
	states map[string]*tfjson.State
}

func newMockStateReader(states map[string]*tfjson.State) *mockStateReader {
	return &mockStateReader{states: states}
}

func (m *mockStateReader) ReadState(_ context.Context, layerPath string) (*tfjson.State, error) {
	s, ok := m.states[layerPath]
	if !ok {
		return &tfjson.State{}, nil
	}
	return s, nil
}

// makeState creates a tfjson.State with resources at the given addresses.
func makeState(addresses ...string) *tfjson.State {
	var resources []*tfjson.StateResource
	for _, addr := range addresses {
		resources = append(resources, &tfjson.StateResource{
			Address: addr,
			Type:    "test_resource",
			Name:    addr,
			Mode:    tfjson.ManagedResourceMode,
		})
	}
	return &tfjson.State{
		Values: &tfjson.StateValues{
			RootModule: &tfjson.StateModule{
				Resources: resources,
			},
		},
	}
}

// makeMigrationContent creates a .tf file content with embedded metadata.
func makeMigrationContent(meta *generator.MigrationMetadata) string {
	metaComment := generator.RenderMetadataComment(meta)
	return "# Generated by statebridge - do not edit manually\n" + metaComment + "\n# test block\nremoved {\n  from = test_resource.example\n}\n"
}

func TestDownloadNoConditions(t *testing.T) {
	mock := newMockUploader()
	content := makeMigrationContent(&generator.MigrationMetadata{
		Resources: []string{"test_resource.example"},
	})
	mock.blobs["migrations/migration.001_test.abcd1234.tf"] = []byte(content)

	dir := t.TempDir()
	// Write a backend.tf so DiscoverBackendConfig works
	writeBackendTF(t, dir)

	dl := NewDownloader(nil, nil, WithUploaderFactory(func(sa, cn string, _ azcore.TokenCredential) (upload.BlobUploader, error) {
		return mock, nil
	}))

	files, err := dl.Download(context.Background(), dir)
	if err != nil {
		t.Fatalf("Download error: %v", err)
	}

	if len(files) != 1 {
		t.Fatalf("expected 1 file written, got %d", len(files))
	}

	// Verify file was written
	outPath := filepath.Join(dir, "migration.001_test.abcd1234.tf")
	if _, err := os.Stat(outPath); errors.Is(err, os.ErrNotExist) {
		t.Errorf("expected file %q to exist", outPath)
	}
}

func TestDownloadConditionMet(t *testing.T) {
	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesExist: []generator.MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"test_resource.existing"}},
			},
		},
		Resources: []string{"test_resource.existing"},
	}

	mock := newMockUploader()
	mock.blobs["migrations/migration.002_move.ef567890.tf"] = []byte(makeMigrationContent(meta))

	dir := t.TempDir()
	writeBackendTF(t, dir)

	dl := NewDownloader(nil, nil, WithUploaderFactory(func(sa, cn string, _ azcore.TokenCredential) (upload.BlobUploader, error) {
		return mock, nil
	}))

	// Without tofu installed, Download will fail when trying to evaluate conditions.
	files, err := dl.Download(context.Background(), dir)
	if err == nil {
		t.Fatal("expected error when evaluating conditions without tofu, got nil")
	}

	// No migration files should have been written.
	if len(files) != 0 {
		t.Errorf("expected no files written, got %d", len(files))
	}
}

func TestEvaluateConditionsResourcesExist(t *testing.T) {
	dl := &Downloader{}
	ctx := context.Background()

	stateWithResource := makeState("test_resource.example")
	reader := newMockStateReader(map[string]*tfjson.State{
		"/test/layer": stateWithResource,
	})

	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesExist: []generator.MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"test_resource.example"}},
			},
		},
	}

	result, err := dl.evaluateConditions(ctx, meta, reader, "/test/layer")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result {
		t.Error("expected conditions to be met")
	}
}

func TestEvaluateConditionsResourcesExistFails(t *testing.T) {
	dl := &Downloader{}
	ctx := context.Background()

	emptyState := makeState() // no resources
	reader := newMockStateReader(map[string]*tfjson.State{
		"/test/layer": emptyState,
	})

	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesExist: []generator.MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"test_resource.missing"}},
			},
		},
	}

	result, err := dl.evaluateConditions(ctx, meta, reader, "/test/layer")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result {
		t.Error("expected conditions to NOT be met")
	}
}

func TestEvaluateConditionsResourcesNotExist(t *testing.T) {
	dl := &Downloader{}
	ctx := context.Background()

	emptyState := makeState()
	reader := newMockStateReader(map[string]*tfjson.State{
		"/test/layer": emptyState,
	})

	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesNotExist: []generator.MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"test_resource.missing"}},
			},
		},
	}

	result, err := dl.evaluateConditions(ctx, meta, reader, "/test/layer")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result {
		t.Error("expected conditions to be met (resource doesn't exist)")
	}
}

func TestEvaluateConditionsResourcesNotExistFails(t *testing.T) {
	dl := &Downloader{}
	ctx := context.Background()

	stateWithResource := makeState("test_resource.existing")
	reader := newMockStateReader(map[string]*tfjson.State{
		"/test/layer": stateWithResource,
	})

	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesNotExist: []generator.MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"test_resource.existing"}},
			},
		},
	}

	result, err := dl.evaluateConditions(ctx, meta, reader, "/test/layer")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result {
		t.Error("expected conditions to NOT be met (resource exists)")
	}
}

func TestEvaluateConditionsCrossLayerWarning(t *testing.T) {
	dl := &Downloader{}
	ctx := context.Background()

	reader := newMockStateReader(nil)

	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesExist: []generator.MetadataResourceCheck{
				{Layer: "./other/layer", Addresses: []string{"test_resource.cross"}},
			},
		},
	}

	// Cross-layer conditions should be treated as met (with warning)
	result, err := dl.evaluateConditions(ctx, meta, reader, "/test/layer")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result {
		t.Error("expected cross-layer condition to be treated as met")
	}
}

func TestEvaluateConditionsNil(t *testing.T) {
	dl := &Downloader{}
	ctx := context.Background()

	meta := &generator.MigrationMetadata{
		Conditions: nil,
	}

	result, err := dl.evaluateConditions(ctx, meta, nil, "/test/layer")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result {
		t.Error("expected nil conditions to pass")
	}
}

func TestDownloadDryRun(t *testing.T) {
	mock := newMockUploader()
	content := makeMigrationContent(&generator.MigrationMetadata{
		Resources: []string{"test_resource.example"},
	})
	mock.blobs["migrations/migration.001_test.abcd1234.tf"] = []byte(content)

	dir := t.TempDir()
	writeBackendTF(t, dir)

	dl := NewDownloader(nil, nil, WithDryRun(true), WithUploaderFactory(func(sa, cn string, _ azcore.TokenCredential) (upload.BlobUploader, error) {
		return mock, nil
	}))

	files, err := dl.Download(context.Background(), dir)
	if err != nil {
		t.Fatalf("Download error: %v", err)
	}

	if len(files) != 1 {
		t.Fatalf("expected 1 file in dry-run, got %d", len(files))
	}

	// File should NOT be written in dry-run mode
	outPath := filepath.Join(dir, "migration.001_test.abcd1234.tf")
	if _, err := os.Stat(outPath); !errors.Is(err, os.ErrNotExist) {
		t.Error("file should not exist in dry-run mode")
	}
}

func TestDownloadNoMigrations(t *testing.T) {
	mock := newMockUploader()

	dir := t.TempDir()
	writeBackendTF(t, dir)

	dl := NewDownloader(nil, nil, WithUploaderFactory(func(sa, cn string, _ azcore.TokenCredential) (upload.BlobUploader, error) {
		return mock, nil
	}))

	files, err := dl.Download(context.Background(), dir)
	if err != nil {
		t.Fatalf("Download error: %v", err)
	}

	if len(files) != 0 {
		t.Errorf("expected 0 files, got %d", len(files))
	}
}

func TestDownloadInvalidMetadataSkipped(t *testing.T) {
	mock := newMockUploader()

	// Valid blob — should be downloaded
	validContent := makeMigrationContent(&generator.MigrationMetadata{
		Resources: []string{"test_resource.good"},
	})
	mock.blobs["migrations/migration.001_valid.aaaa1111.tf"] = []byte(validContent)

	// Blob with corrupt metadata — should be skipped, not written
	corruptContent := "# Generated by statebridge - do not edit manually\n" +
		"#\n" +
		"# statebridge:metadata:begin\n" +
		"# {invalid json\n" +
		"# statebridge:metadata:end\n" +
		"\nremoved {\n  from = test_resource.bad\n}\n"
	mock.blobs["migrations/migration.002_corrupt.bbbb2222.tf"] = []byte(corruptContent)

	dir := t.TempDir()
	writeBackendTF(t, dir)

	dl := NewDownloader(nil, nil, WithUploaderFactory(func(sa, cn string, _ azcore.TokenCredential) (upload.BlobUploader, error) {
		return mock, nil
	}))

	files, err := dl.Download(context.Background(), dir)
	if err != nil {
		t.Fatalf("Download error: %v", err)
	}

	// Only the valid blob should be written
	if len(files) != 1 {
		t.Fatalf("expected 1 file written, got %d: %v", len(files), files)
	}

	// Valid file should exist
	validPath := filepath.Join(dir, "migration.001_valid.aaaa1111.tf")
	if _, err := os.Stat(validPath); errors.Is(err, os.ErrNotExist) {
		t.Errorf("expected valid file %q to exist", validPath)
	}

	// Corrupt file should NOT exist
	corruptPath := filepath.Join(dir, "migration.002_corrupt.bbbb2222.tf")
	if _, err := os.Stat(corruptPath); !errors.Is(err, os.ErrNotExist) {
		t.Errorf("expected corrupt file %q to NOT exist", corruptPath)
	}
}

// writeBackendTF writes a minimal backend.tf to the directory for DiscoverBackendConfig.
func writeBackendTF(t *testing.T, dir string) {
	t.Helper()
	err := os.WriteFile(filepath.Join(dir, "backend.tf"), []byte(`
terraform {
  backend "azurerm" {
    storage_account_name = "testacct"
    container_name       = "testcontainer"
  }
}
`), 0o644)
	if err != nil {
		t.Fatal(err)
	}
}

func writeBackendTFWithKey(t *testing.T, dir, key string) {
	t.Helper()
	err := os.WriteFile(filepath.Join(dir, "backend.tf"), []byte(fmt.Sprintf(`
terraform {
  backend "azurerm" {
    storage_account_name = "testacct"
    container_name       = "testcontainer"
    key                  = %q
  }
}
`, key)), 0o644)
	if err != nil {
		t.Fatal(err)
	}
}

func TestDownloadSourceLayerScoping(t *testing.T) {
	newDownloader := func(mock upload.BlobUploader) *Downloader {
		return NewDownloader(nil, nil, WithUploaderFactory(func(_, _ string, _ azcore.TokenCredential) (upload.BlobUploader, error) {
			return mock, nil
		}))
	}

	t.Run("blob owned by another layer is skipped", func(t *testing.T) {
		mock := newMockUploader()
		mock.blobs["migrations/migration.001_test.abcd1234.tf"] = []byte(makeMigrationContent(&generator.MigrationMetadata{
			Version:     generator.CurrentMetadataVersion,
			SourceLayer: &generator.MetadataSourceLayer{StorageAccountName: "testacct", ContainerName: "testcontainer", Key: "other.tfstate"},
			Resources:   []string{"test_resource.example"},
		}))

		dir := t.TempDir()
		writeBackendTFWithKey(t, dir, "compute.tfstate")

		files, err := newDownloader(mock).Download(context.Background(), dir)
		if err != nil {
			t.Fatalf("Download error: %v", err)
		}
		if len(files) != 0 {
			t.Fatalf("expected 0 files (blob belongs to another layer), got %d", len(files))
		}
	})

	t.Run("blob matching this layer is downloaded", func(t *testing.T) {
		mock := newMockUploader()
		mock.blobs["migrations/migration.001_test.abcd1234.tf"] = []byte(makeMigrationContent(&generator.MigrationMetadata{
			Version:     generator.CurrentMetadataVersion,
			SourceLayer: &generator.MetadataSourceLayer{StorageAccountName: "testacct", ContainerName: "testcontainer", Key: "compute.tfstate"},
			Resources:   []string{"test_resource.example"},
		}))

		dir := t.TempDir()
		writeBackendTFWithKey(t, dir, "compute.tfstate")

		files, err := newDownloader(mock).Download(context.Background(), dir)
		if err != nil {
			t.Fatalf("Download error: %v", err)
		}
		if len(files) != 1 {
			t.Fatalf("expected 1 file (matches this layer), got %d", len(files))
		}
	})

	t.Run("legacy blob without source_layer is downloaded", func(t *testing.T) {
		mock := newMockUploader()
		mock.blobs["migrations/migration.001_test.abcd1234.tf"] = []byte(makeMigrationContent(&generator.MigrationMetadata{
			Resources: []string{"test_resource.example"},
		}))

		dir := t.TempDir()
		writeBackendTFWithKey(t, dir, "compute.tfstate")

		files, err := newDownloader(mock).Download(context.Background(), dir)
		if err != nil {
			t.Fatalf("Download error: %v", err)
		}
		if len(files) != 1 {
			t.Fatalf("expected 1 file (legacy, unscoped), got %d", len(files))
		}
	})

	t.Run("indeterminate key falls back to download", func(t *testing.T) {
		mock := newMockUploader()
		mock.blobs["migrations/migration.001_test.abcd1234.tf"] = []byte(makeMigrationContent(&generator.MigrationMetadata{
			Version:     generator.CurrentMetadataVersion,
			SourceLayer: &generator.MetadataSourceLayer{StorageAccountName: "testacct", ContainerName: "testcontainer", Key: "compute.tfstate"},
			Resources:   []string{"test_resource.example"},
		}))

		dir := t.TempDir()
		// Backend has no key => this layer's key is undeterminable => lenient.
		writeBackendTF(t, dir)

		files, err := newDownloader(mock).Download(context.Background(), dir)
		if err != nil {
			t.Fatalf("Download error: %v", err)
		}
		if len(files) != 1 {
			t.Fatalf("expected 1 file (indeterminate, lenient fallback), got %d", len(files))
		}
	})
}

// fakeCredential is a distinguishable azcore.TokenCredential stand-in used to
// verify identity (pointer equality) of the credential passed to the
// uploader factory, without performing any real token acquisition.
type fakeCredential struct{}

func (f *fakeCredential) GetToken(context.Context, policy.TokenRequestOptions) (azcore.AccessToken, error) {
	return azcore.AccessToken{}, nil
}

func writeBackendTFWithCredentials(t *testing.T, dir, extraAttrs string) {
	t.Helper()
	content := "\nterraform {\n  backend \"azurerm\" {\n    storage_account_name = \"testacct\"\n    container_name       = \"testcontainer\"\n" +
		extraAttrs + "  }\n}\n"
	if err := os.WriteFile(filepath.Join(dir, "backend.tf"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestDownload_UsesLayerSpecificCredential(t *testing.T) {
	mock := newMockUploader()

	dir := t.TempDir()
	writeBackendTFWithCredentials(t, dir, `    client_id = "layer-client"
    tenant_id = "layer-tenant"
    use_cli   = true
`)

	base := &fakeCredential{}
	var gotCred azcore.TokenCredential
	dl := NewDownloader(base, nil, WithUploaderFactory(func(_, _ string, cred azcore.TokenCredential) (upload.BlobUploader, error) {
		gotCred = cred
		return mock, nil
	}))

	if _, err := dl.Download(context.Background(), dir); err != nil {
		t.Fatalf("Download error: %v", err)
	}
	if gotCred == azcore.TokenCredential(base) {
		t.Error("expected the uploader factory to receive a layer-specific credential, not the base credential")
	}
}

func TestDownload_NoLayerCredentialsUsesBase(t *testing.T) {
	mock := newMockUploader()

	dir := t.TempDir()
	writeBackendTF(t, dir)

	base := &fakeCredential{}
	var gotCred azcore.TokenCredential
	dl := NewDownloader(base, nil, WithUploaderFactory(func(_, _ string, cred azcore.TokenCredential) (upload.BlobUploader, error) {
		gotCred = cred
		return mock, nil
	}))

	if _, err := dl.Download(context.Background(), dir); err != nil {
		t.Fatalf("Download error: %v", err)
	}
	if gotCred != azcore.TokenCredential(base) {
		t.Error("expected the uploader factory to receive the base credential when the layer has no credential values")
	}
}

func TestDownload_CredentialErrorPropagates(t *testing.T) {
	dir := t.TempDir()
	writeBackendTFWithCredentials(t, dir, `    client_id = "layer-client"
    tenant_id = "layer-tenant"
    use_msi   = "not-a-bool"
`)

	dl := NewDownloader(&fakeCredential{}, nil, WithUploaderFactory(func(_, _ string, _ azcore.TokenCredential) (upload.BlobUploader, error) {
		return newMockUploader(), nil
	}))

	_, err := dl.Download(context.Background(), dir)
	if err == nil {
		t.Fatal("expected error due to invalid use_msi value in layer backend config")
	}
}
