package upload

import (
	"context"
	"strings"
	"testing"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"

	"github.com/terraprovider/statebridge/pkg/generator"
)

// migrationBlobForLayer renders migration .tf content whose metadata records the
// given backend coordinates as its source layer. An empty key produces a
// descriptor without a key; passing legacy=true omits source_layer entirely.
func migrationBlobForLayer(account, container, key string, legacy bool) []byte {
	meta := &generator.MigrationMetadata{
		Version:   generator.CurrentMetadataVersion,
		Resources: []string{"test_resource.x"},
	}
	if !legacy {
		meta.SourceLayer = &generator.MetadataSourceLayer{
			StorageAccountName: account,
			ContainerName:      container,
			Key:                key,
		}
	}
	return []byte("# Generated by statebridge - do not edit manually\n" +
		generator.RenderMetadataComment(meta) +
		"\nremoved {\n  from = test_resource.x\n}\n")
}

func deletedContains(deleted []string, blobName string) bool {
	for _, d := range deleted {
		if d == blobName {
			return true
		}
	}
	return false
}

func TestCleanupOldVersions_LayerScoping(t *testing.T) {
	ctx := context.Background()
	config := &BackendConfig{StorageAccountName: "acct", ContainerName: "shared", Key: "compute.tfstate"}

	mine := "migrations/migration.001_move.mine0000.tf"
	other := "migrations/migration.001_move.other000.tf"
	legacy := "migrations/migration.001_move.legacy00.tf"

	mock := newMockUploader()
	mock.setBlobs("migrations/migration.001_move.", []string{mine, other, legacy})
	mock.setBlobData(mine, migrationBlobForLayer("acct", "shared", "compute.tfstate", false))
	mock.setBlobData(other, migrationBlobForLayer("acct", "shared", "network.tfstate", false))
	mock.setBlobData(legacy, migrationBlobForLayer("", "", "", true))

	mgr := &Manager{uploadedInSession: make(map[string]bool), configCache: make(map[string]*BackendConfig)}
	if err := mgr.cleanupOldVersions(ctx, mock, "migration.001_move.newnew99.tf", config); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if deletedContains(mock.deleted, other) {
		t.Errorf("other layer's blob %q must not be deleted", other)
	}
	if !deletedContains(mock.deleted, mine) {
		t.Errorf("this layer's old version %q should be deleted", mine)
	}
	if !deletedContains(mock.deleted, legacy) {
		t.Errorf("legacy old version %q should be deleted", legacy)
	}
}

func TestCheckActiveBlobs_LayerScoping(t *testing.T) {
	ctx := context.Background()
	config := &BackendConfig{StorageAccountName: "acct", ContainerName: "shared", Key: "compute.tfstate"}

	// Guard checker always reports "active" — so the only thing that can prevent
	// a block is the layer-ownership skip.
	guardActive := func(_ context.Context, _ []byte, _ string) (bool, error) { return true, nil }

	t.Run("other-layer active blob does not block upload", func(t *testing.T) {
		other := "migrations/migration.001_move.other000.tf"
		mock := newMockUploader()
		mock.setBlobs("migrations/migration.001_move.", []string{other})
		mock.setBlobData(other, migrationBlobForLayer("acct", "shared", "network.tfstate", false))

		mgr := NewManager(nil, nil, WithGuardChecker(guardActive))
		err := mgr.checkActiveBlobs(ctx, mock, "migration.001_move.newnew99.tf", "/layers/compute", config)
		if err != nil {
			t.Fatalf("expected no error (other layer skipped), got: %v", err)
		}
	})

	t.Run("matching active blob blocks upload", func(t *testing.T) {
		mineOld := "migrations/migration.001_move.mineold0.tf"
		mock := newMockUploader()
		mock.setBlobs("migrations/migration.001_move.", []string{mineOld})
		mock.setBlobData(mineOld, migrationBlobForLayer("acct", "shared", "compute.tfstate", false))

		mgr := NewManager(nil, nil, WithGuardChecker(guardActive))
		err := mgr.checkActiveBlobs(ctx, mock, "migration.001_move.newnew99.tf", "/layers/compute", config)
		if err == nil || !strings.Contains(err.Error(), "refusing to overwrite") {
			t.Fatalf("expected refusing-to-overwrite error for own active blob, got: %v", err)
		}
	})
}

func TestPruneStems_LayerScoping(t *testing.T) {
	ctx := context.Background()
	layerPath := "/layers/compute"
	config := &BackendConfig{StorageAccountName: "acct", ContainerName: "shared", Key: "compute.tfstate"}

	mine := "migrations/migration.001_move.mine0000.tf"
	other := "migrations/migration.001_move.other000.tf"

	mock := newMockUploader()
	mock.setBlobs("migrations/migration.001_move.", []string{mine, other})
	mock.setBlobData(mine, migrationBlobForLayer("acct", "shared", "compute.tfstate", false))
	mock.setBlobData(other, migrationBlobForLayer("acct", "shared", "network.tfstate", false))

	mgr := NewManager(nil, nil)
	mgr.configCache[layerPath] = config
	mgr.WithUploaderFactory(func(_, _ string, _ azcore.TokenCredential) (BlobUploader, error) {
		return mock, nil
	})

	pruned, err := mgr.PruneStems(ctx, []string{"001_move"}, []string{layerPath})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if pruned != 1 {
		t.Errorf("expected 1 pruned, got %d", pruned)
	}
	if deletedContains(mock.deleted, other) {
		t.Errorf("other layer's blob %q must not be pruned", other)
	}
	if !deletedContains(mock.deleted, mine) {
		t.Errorf("this layer's blob %q should be pruned", mine)
	}
}
