package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestImportBlock_Render(t *testing.T) {
	b := &ImportBlock{
		To:    "aws_instance.web",
		ID:    "i-0abc123def456",
		Layer: "./layers/app",
	}

	expected := `import {
  to = aws_instance.web
  id = "i-0abc123def456"
}`
	result := b.Render()
	if result != expected {
		t.Errorf("expected:\n%s\ngot:\n%s", expected, result)
	}
}

func TestImportBlock_RenderWithProvider(t *testing.T) {
	b := &ImportBlock{
		To:       "aws_db_instance.primary",
		ID:       "my-database",
		Provider: "aws.useast1",
		Layer:    "./layers/db",
	}

	expected := `import {
  to       = aws_db_instance.primary
  id       = "my-database"
  provider = aws.useast1
}`
	result := b.Render()
	if result != expected {
		t.Errorf("expected:\n%s\ngot:\n%s", expected, result)
	}
}

func TestImportBlock_RenderWithForEachKey(t *testing.T) {
	b := &ImportBlock{
		To:    `aws_s3_bucket.data["my-bucket"]`,
		ID:    "my-bucket-id",
		Layer: "./layers/storage",
	}

	expected := `import {
  to = aws_s3_bucket.data["my-bucket"]
  id = "my-bucket-id"
}`
	result := b.Render()
	if result != expected {
		t.Errorf("expected:\n%s\ngot:\n%s", expected, result)
	}
}

func TestMovedBlock_Render(t *testing.T) {
	b := &MovedBlock{
		From:  "module.old_vpc",
		To:    "module.new_vpc",
		Layer: "./layers/networking",
	}

	expected := `moved {
  from = module.old_vpc
  to   = module.new_vpc
}`
	result := b.Render()
	if result != expected {
		t.Errorf("expected:\n%s\ngot:\n%s", expected, result)
	}
}

func TestMovedBlock_RenderWithForEachKey(t *testing.T) {
	b := &MovedBlock{
		From:  `aws_security_group.sg["key-a"]`,
		To:    `aws_security_group.sg["key-b"]`,
		Layer: "./layers/networking",
	}

	expected := `moved {
  from = aws_security_group.sg["key-a"]
  to   = aws_security_group.sg["key-b"]
}`
	result := b.Render()
	if result != expected {
		t.Errorf("expected:\n%s\ngot:\n%s", expected, result)
	}
}

func TestRemovedBlock_Render_DestroyFalse(t *testing.T) {
	b := &RemovedBlock{
		From:    "aws_iam_role.deprecated",
		Destroy: false,
		Layer:   "./layers/legacy",
	}

	expected := `removed {
  from = aws_iam_role.deprecated

  lifecycle {
    destroy = false
  }
}`
	result := b.Render()
	if result != expected {
		t.Errorf("expected:\n%s\ngot:\n%s", expected, result)
	}
}

func TestRemovedBlock_Render_DestroyTrue(t *testing.T) {
	b := &RemovedBlock{
		From:    "aws_instance.old",
		Destroy: true,
		Layer:   "./layers/compute",
	}

	expected := `removed {
  from = aws_instance.old

  lifecycle {
    destroy = true
  }
}`
	result := b.Render()
	if result != expected {
		t.Errorf("expected:\n%s\ngot:\n%s", expected, result)
	}
}

func TestBlock_LayerPath(t *testing.T) {
	tests := []struct {
		name  string
		block Block
		layer string
	}{
		{"import", &ImportBlock{Layer: "./layers/app"}, "./layers/app"},
		{"moved", &MovedBlock{Layer: "./layers/net"}, "./layers/net"},
		{"removed", &RemovedBlock{Layer: "./layers/old"}, "./layers/old"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if tt.block.LayerPath() != tt.layer {
				t.Errorf("expected layer %q, got %q", tt.layer, tt.block.LayerPath())
			}
		})
	}
}

func TestBlock_Comment(t *testing.T) {
	b := &ImportBlock{Description: "Import web server"}
	if b.Comment() != "Import web server" {
		t.Errorf("expected comment %q, got %q", "Import web server", b.Comment())
	}
}

func TestWriter_GroupedByLayer(t *testing.T) {
	w := NewWriter()
	w.AddBlock(&ImportBlock{To: "a", ID: "1", Layer: "./layers/app"})
	w.AddBlock(&RemovedBlock{From: "b", Layer: "./layers/compute"})
	w.AddBlock(&MovedBlock{From: "c", To: "d", Layer: "./layers/app"})

	grouped := w.GroupedByLayer()
	if len(grouped["./layers/app"]) != 2 {
		t.Errorf("expected 2 blocks for app layer, got %d", len(grouped["./layers/app"]))
	}
	if len(grouped["./layers/compute"]) != 1 {
		t.Errorf("expected 1 block for compute layer, got %d", len(grouped["./layers/compute"]))
	}
}

func TestWriter_RenderLayer(t *testing.T) {
	w := NewWriter()
	w.AddBlock(&MovedBlock{
		From:        "module.old_vpc",
		To:          "module.new_vpc",
		Layer:       "./layers/networking",
		Description: "Rename VPC module",
	})

	content := w.RenderLayer("./layers/networking")
	if !strings.Contains(content, "# Generated by tfmigrate") {
		t.Error("expected header comment in output")
	}
	if !strings.Contains(content, "module.old_vpc") {
		t.Error("expected moved block from address in output")
	}
	if !strings.Contains(content, "module.new_vpc") {
		t.Error("expected moved block to address in output")
	}
	if !strings.Contains(content, "# Rename VPC module") {
		t.Error("expected description comment in output")
	}
}

func TestWriter_RenderLayer_Empty(t *testing.T) {
	w := NewWriter()
	content := w.RenderLayer("./nonexistent")
	if content != "" {
		t.Errorf("expected empty string for nonexistent layer, got %q", content)
	}
}

func TestWriter_RenderAll_MultipleLayersAggregated(t *testing.T) {
	w := NewWriter()
	w.AddBlock(&RemovedBlock{From: "aws_instance.web", Layer: "./src"})
	w.AddBlock(&ImportBlock{To: "aws_instance.web", ID: "i-123", Layer: "./dst"})
	w.AddBlock(&RemovedBlock{From: "aws_instance.api", Layer: "./src"})

	all := w.RenderAll()

	srcContent := all["./src"]
	if strings.Count(srcContent, "removed {") != 2 {
		t.Errorf("expected 2 removed blocks in source layer, got content:\n%s", srcContent)
	}

	dstContent := all["./dst"]
	if strings.Count(dstContent, "import {") != 1 {
		t.Errorf("expected 1 import block in dest layer, got content:\n%s", dstContent)
	}
}

func TestWriter_WriteAll(t *testing.T) {
	dir := t.TempDir()
	layerDir := filepath.Join(dir, "layers", "app")
	if err := os.MkdirAll(layerDir, 0o755); err != nil {
		t.Fatal(err)
	}

	w := NewWriter()
	w.AddBlock(&ImportBlock{
		To:    "aws_instance.web",
		ID:    "i-123",
		Layer: layerDir,
	})

	files, err := w.WriteAll()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(files) != 1 {
		t.Fatalf("expected 1 file, got %d", len(files))
	}

	content, err := os.ReadFile(files[0])
	if err != nil {
		t.Fatalf("reading output file: %v", err)
	}

	if !strings.Contains(string(content), "import {") {
		t.Error("expected import block in output file")
	}
	if !strings.Contains(string(content), `id = "i-123"`) {
		t.Error("expected import ID in output file")
	}
}

func TestWriter_WriteAll_DryRun(t *testing.T) {
	w := NewWriter()
	w.DryRun = true
	w.AddBlock(&ImportBlock{
		To:    "aws_instance.web",
		ID:    "i-123",
		Layer: "/nonexistent/layer",
	})

	files, err := w.WriteAll()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(files) != 1 {
		t.Fatalf("expected 1 file path, got %d", len(files))
	}

	// File should not actually exist
	if _, err := os.Stat(files[0]); !os.IsNotExist(err) {
		t.Error("expected file to not exist in dry-run mode")
	}
}

func TestWriter_CustomOutputFilename(t *testing.T) {
	dir := t.TempDir()
	w := NewWriter()
	w.OutputFilename = "custom_migration.tf"
	w.AddBlock(&ImportBlock{
		To:    "aws_instance.web",
		ID:    "i-123",
		Layer: dir,
	})

	files, err := w.WriteAll()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	expected := filepath.Join(dir, "custom_migration.tf")
	if files[0] != expected {
		t.Errorf("expected path %q, got %q", expected, files[0])
	}
}
