package generator

import (
	"strings"
	"testing"
)

func TestRenderAndParseMetadataRoundTrip(t *testing.T) {
	meta := &MigrationMetadata{
		Conditions: &MetadataCondition{
			ResourcesExist: []MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"azurerm_resource_group.example"}},
			},
			ResourcesNotExist: []MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"azurerm_virtual_network.old"}},
			},
		},
		InitArgs:  []string{"-backend-config=storage_account_name=myacct", "-reconfigure"},
		Resources: []string{"azurerm_resource_group.example", "azurerm_virtual_network.main"},
	}

	rendered := RenderMetadataComment(meta)
	if rendered == "" {
		t.Fatal("RenderMetadataComment returned empty string")
	}

	// Verify markers present
	if !strings.Contains(rendered, "tfmigrate:metadata:begin") {
		t.Error("missing begin marker")
	}
	if !strings.Contains(rendered, "tfmigrate:metadata:end") {
		t.Error("missing end marker")
	}

	parsed, err := ParseMetadataComment(rendered)
	if err != nil {
		t.Fatalf("ParseMetadataComment error: %v", err)
	}
	if parsed == nil {
		t.Fatal("ParseMetadataComment returned nil")
	}

	// Verify round-trip
	if len(parsed.Resources) != 2 {
		t.Errorf("expected 2 resources, got %d", len(parsed.Resources))
	}
	if parsed.Resources[0] != "azurerm_resource_group.example" {
		t.Errorf("resource[0] = %q", parsed.Resources[0])
	}
	if len(parsed.InitArgs) != 2 {
		t.Errorf("expected 2 init args, got %d", len(parsed.InitArgs))
	}
	if parsed.Conditions == nil {
		t.Fatal("conditions is nil after round-trip")
	}
	if len(parsed.Conditions.ResourcesExist) != 1 {
		t.Errorf("expected 1 resources_exist check, got %d", len(parsed.Conditions.ResourcesExist))
	}
	if parsed.Conditions.ResourcesExist[0].Layer != "." {
		t.Errorf("resources_exist layer = %q, want %q", parsed.Conditions.ResourcesExist[0].Layer, ".")
	}
	if len(parsed.Conditions.ResourcesNotExist) != 1 {
		t.Errorf("expected 1 resources_not_exist check, got %d", len(parsed.Conditions.ResourcesNotExist))
	}
}

func TestRenderMetadataCommentNil(t *testing.T) {
	result := RenderMetadataComment(nil)
	if result != "" {
		t.Errorf("expected empty string for nil metadata, got %q", result)
	}
}

func TestParseMetadataCommentNoMetadata(t *testing.T) {
	content := `# Generated by tfmigrate - do not edit manually

import {
  to = azurerm_resource_group.example
  id = "/subscriptions/xxx/resourceGroups/example"
}
`
	meta, err := ParseMetadataComment(content)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if meta != nil {
		t.Error("expected nil for content without metadata")
	}
}

func TestParseMetadataFromFullTfFile(t *testing.T) {
	content := `# Generated by tfmigrate - do not edit manually
#
# tfmigrate:metadata:begin
# {"conditions":{"resources_exist":[{"layer":".","addresses":["azurerm_resource_group.rg"]}]},"init_args":["-reconfigure"],"resources":["azurerm_resource_group.rg","azurerm_virtual_network.vnet"]}
# tfmigrate:metadata:end

# Move resource group
import {
  to = azurerm_resource_group.rg
  id = "/subscriptions/xxx/resourceGroups/rg"
}

# Move virtual network
import {
  to = azurerm_virtual_network.vnet
  id = "/subscriptions/xxx/resourceGroups/rg/providers/Microsoft.Network/virtualNetworks/vnet"
}
`

	meta, err := ParseMetadataComment(content)
	if err != nil {
		t.Fatalf("ParseMetadataComment error: %v", err)
	}
	if meta == nil {
		t.Fatal("expected metadata, got nil")
	}

	if len(meta.Resources) != 2 {
		t.Errorf("expected 2 resources, got %d", len(meta.Resources))
	}
	if len(meta.InitArgs) != 1 || meta.InitArgs[0] != "-reconfigure" {
		t.Errorf("init_args = %v", meta.InitArgs)
	}
	if meta.Conditions == nil || len(meta.Conditions.ResourcesExist) != 1 {
		t.Error("expected 1 resources_exist condition")
	}
}

func TestParseMetadataCommentMalformed(t *testing.T) {
	// Begin marker but no end marker
	content := "# tfmigrate:metadata:begin\n# {}\n"
	_, err := ParseMetadataComment(content)
	if err == nil {
		t.Error("expected error for missing end marker")
	}
}

func TestExtractResourceAddresses(t *testing.T) {
	blocks := []Block{
		&ImportBlock{To: "azurerm_resource_group.rg", Layer: "/layer", Source: "test.yaml"},
		&MovedBlock{From: "azurerm_vnet.old", To: "azurerm_vnet.new", Layer: "/layer", Source: "test.yaml"},
		&RemovedBlock{From: "azurerm_resource_group.rg", Layer: "/layer", Source: "test.yaml"},
		&ImportBlock{To: "azurerm_subnet.sub", Layer: "/layer", Source: "test.yaml"},
	}

	addrs := ExtractResourceAddresses(blocks)

	// Expected: deduplicated + sorted
	expected := []string{
		"azurerm_resource_group.rg",
		"azurerm_subnet.sub",
		"azurerm_vnet.new",
		"azurerm_vnet.old",
	}

	if len(addrs) != len(expected) {
		t.Fatalf("expected %d addresses, got %d: %v", len(expected), len(addrs), addrs)
	}
	for i, addr := range addrs {
		if addr != expected[i] {
			t.Errorf("addr[%d] = %q, want %q", i, addr, expected[i])
		}
	}
}

func TestExtractResourceAddressesEmpty(t *testing.T) {
	addrs := ExtractResourceAddresses(nil)
	if len(addrs) != 0 {
		t.Errorf("expected 0 addresses for nil blocks, got %d", len(addrs))
	}
}

func TestRelativizeCondition(t *testing.T) {
	cond := &MetadataCondition{
		ResourcesExist: []MetadataResourceCheck{
			{Layer: "./layers/compute", Addresses: []string{"azurerm_vm.web"}},
			{Layer: "./layers/network", Addresses: []string{"azurerm_vnet.main"}},
		},
		ResourcesNotExist: []MetadataResourceCheck{
			{Layer: "./layers/compute", Addresses: []string{"azurerm_vm.old"}},
		},
	}

	result := RelativizeCondition(cond, "./layers/compute")

	if result == nil {
		t.Fatal("expected non-nil result")
	}

	// The compute layer should be relativized to "."
	if result.ResourcesExist[0].Layer != "." {
		t.Errorf("expected layer '.' for compute, got %q", result.ResourcesExist[0].Layer)
	}
	// The network layer should remain as-is
	if result.ResourcesExist[1].Layer != "./layers/network" {
		t.Errorf("expected layer './layers/network', got %q", result.ResourcesExist[1].Layer)
	}
	// resources_not_exist should also be relativized
	if result.ResourcesNotExist[0].Layer != "." {
		t.Errorf("expected layer '.' for compute not_exist, got %q", result.ResourcesNotExist[0].Layer)
	}

	// Verify original was not modified
	if cond.ResourcesExist[0].Layer != "./layers/compute" {
		t.Error("original condition was modified")
	}
}

func TestRelativizeConditionNil(t *testing.T) {
	result := RelativizeCondition(nil, "/some/path")
	if result != nil {
		t.Error("expected nil for nil condition")
	}
}

func TestMetadataNoConditions(t *testing.T) {
	meta := &MigrationMetadata{
		Resources: []string{"azurerm_resource_group.rg"},
	}

	rendered := RenderMetadataComment(meta)
	parsed, err := ParseMetadataComment(rendered)
	if err != nil {
		t.Fatalf("error: %v", err)
	}
	if parsed.Conditions != nil {
		t.Error("expected nil conditions")
	}
	if len(parsed.Resources) != 1 {
		t.Errorf("expected 1 resource, got %d", len(parsed.Resources))
	}
}
