package generator

import (
	"strings"
	"testing"
)

func TestRenderAndParseMetadataRoundTrip(t *testing.T) {
	meta := &MigrationMetadata{
		Conditions: &MetadataCondition{
			ResourcesExist: []MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"azurerm_resource_group.example"}},
			},
			ResourcesNotExist: []MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"azurerm_virtual_network.old"}},
			},
		},
		Resources: []string{"azurerm_resource_group.example", "azurerm_virtual_network.main"},
	}

	rendered := RenderMetadataComment(meta)
	if rendered == "" {
		t.Fatal("RenderMetadataComment returned empty string")
	}

	// Verify markers present
	if !strings.Contains(rendered, "statebridge:metadata:begin") {
		t.Error("missing begin marker")
	}
	if !strings.Contains(rendered, "statebridge:metadata:end") {
		t.Error("missing end marker")
	}

	parsed, err := ParseMetadataComment(rendered)
	if err != nil {
		t.Fatalf("ParseMetadataComment error: %v", err)
	}
	if parsed == nil {
		t.Fatal("ParseMetadataComment returned nil")
	}

	// Verify round-trip
	if len(parsed.Resources) != 2 {
		t.Errorf("expected 2 resources, got %d", len(parsed.Resources))
	}
	if parsed.Resources[0] != "azurerm_resource_group.example" {
		t.Errorf("resource[0] = %q", parsed.Resources[0])
	}
	if parsed.Conditions == nil {
		t.Fatal("conditions is nil after round-trip")
	}
	if len(parsed.Conditions.ResourcesExist) != 1 {
		t.Errorf("expected 1 resources_exist check, got %d", len(parsed.Conditions.ResourcesExist))
	}
	if parsed.Conditions.ResourcesExist[0].Layer != "." {
		t.Errorf("resources_exist layer = %q, want %q", parsed.Conditions.ResourcesExist[0].Layer, ".")
	}
	if len(parsed.Conditions.ResourcesNotExist) != 1 {
		t.Errorf("expected 1 resources_not_exist check, got %d", len(parsed.Conditions.ResourcesNotExist))
	}
}

func TestRenderMetadataCommentNil(t *testing.T) {
	result := RenderMetadataComment(nil)
	if result != "" {
		t.Errorf("expected empty string for nil metadata, got %q", result)
	}
}

func TestParseMetadataCommentNoMetadata(t *testing.T) {
	content := `# Generated by statebridge - do not edit manually

import {
  to = azurerm_resource_group.example
  id = "/subscriptions/xxx/resourceGroups/example"
}
`
	meta, err := ParseMetadataComment(content)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if meta != nil {
		t.Error("expected nil for content without metadata")
	}
}

func TestParseMetadataFromFullTfFile(t *testing.T) {
	content := `# Generated by statebridge - do not edit manually
#
# statebridge:metadata:begin
# {"conditions":{"resources_exist":[{"layer":".","addresses":["azurerm_resource_group.rg"]}]},"resources":["azurerm_resource_group.rg","azurerm_virtual_network.vnet"]}
# statebridge:metadata:end

# Move resource group
import {
  to = azurerm_resource_group.rg
  id = "/subscriptions/xxx/resourceGroups/rg"
}

# Move virtual network
import {
  to = azurerm_virtual_network.vnet
  id = "/subscriptions/xxx/resourceGroups/rg/providers/Microsoft.Network/virtualNetworks/vnet"
}
`

	meta, err := ParseMetadataComment(content)
	if err != nil {
		t.Fatalf("ParseMetadataComment error: %v", err)
	}
	if meta == nil {
		t.Fatal("expected metadata, got nil")
	}

	if len(meta.Resources) != 2 {
		t.Errorf("expected 2 resources, got %d", len(meta.Resources))
	}
	if meta.Conditions == nil || len(meta.Conditions.ResourcesExist) != 1 {
		t.Error("expected 1 resources_exist condition")
	}
}

func TestParseMetadataCommentMalformed(t *testing.T) {
	// Begin marker but no end marker
	content := "# statebridge:metadata:begin\n# {}\n"
	_, err := ParseMetadataComment(content)
	if err == nil {
		t.Error("expected error for missing end marker")
	}
}

func TestExtractResourceAddresses(t *testing.T) {
	blocks := []Block{
		&ImportBlock{To: "azurerm_resource_group.rg", Layer: "/layer", Source: "test.yaml"},
		&MovedBlock{From: "azurerm_vnet.old", To: "azurerm_vnet.new", Layer: "/layer", Source: "test.yaml"},
		&RemovedBlock{From: "azurerm_resource_group.rg", Layer: "/layer", Source: "test.yaml"},
		&ImportBlock{To: "azurerm_subnet.sub", Layer: "/layer", Source: "test.yaml"},
	}

	addrs := ExtractResourceAddresses(blocks)

	// Expected: deduplicated + sorted
	expected := []string{
		"azurerm_resource_group.rg",
		"azurerm_subnet.sub",
		"azurerm_vnet.new",
		"azurerm_vnet.old",
	}

	if len(addrs) != len(expected) {
		t.Fatalf("expected %d addresses, got %d: %v", len(expected), len(addrs), addrs)
	}
	for i, addr := range addrs {
		if addr != expected[i] {
			t.Errorf("addr[%d] = %q, want %q", i, addr, expected[i])
		}
	}
}

func TestExtractResourceAddressesEmpty(t *testing.T) {
	addrs := ExtractResourceAddresses(nil)
	if len(addrs) != 0 {
		t.Errorf("expected 0 addresses for nil blocks, got %d", len(addrs))
	}
}

func TestRelativizeCondition(t *testing.T) {
	cond := &MetadataCondition{
		ResourcesExist: []MetadataResourceCheck{
			{Layer: "./layers/compute", Addresses: []string{"azurerm_vm.web"}},
			{Layer: "./layers/network", Addresses: []string{"azurerm_vnet.main"}},
		},
		ResourcesNotExist: []MetadataResourceCheck{
			{Layer: "./layers/compute", Addresses: []string{"azurerm_vm.old"}},
		},
	}

	result := RelativizeCondition(cond, "./layers/compute")

	if result == nil {
		t.Fatal("expected non-nil result")
	}

	// The compute layer should be relativized to "."
	if result.ResourcesExist[0].Layer != "." {
		t.Errorf("expected layer '.' for compute, got %q", result.ResourcesExist[0].Layer)
	}
	// The network layer should remain as-is
	if result.ResourcesExist[1].Layer != "./layers/network" {
		t.Errorf("expected layer './layers/network', got %q", result.ResourcesExist[1].Layer)
	}
	// resources_not_exist should also be relativized
	if result.ResourcesNotExist[0].Layer != "." {
		t.Errorf("expected layer '.' for compute not_exist, got %q", result.ResourcesNotExist[0].Layer)
	}

	// Verify original was not modified
	if cond.ResourcesExist[0].Layer != "./layers/compute" {
		t.Error("original condition was modified")
	}
}

func TestRelativizeConditionNil(t *testing.T) {
	result := RelativizeCondition(nil, "/some/path")
	if result != nil {
		t.Error("expected nil for nil condition")
	}
}

func TestMetadataNoConditions(t *testing.T) {
	meta := &MigrationMetadata{
		Resources: []string{"azurerm_resource_group.rg"},
	}

	rendered := RenderMetadataComment(meta)
	parsed, err := ParseMetadataComment(rendered)
	if err != nil {
		t.Fatalf("error: %v", err)
	}
	if parsed.Conditions != nil {
		t.Error("expected nil conditions")
	}
	if len(parsed.Resources) != 1 {
		t.Errorf("expected 1 resource, got %d", len(parsed.Resources))
	}
}

func TestInferConditionsMixed(t *testing.T) {
	blocks := []Block{
		&RemovedBlock{From: "azurerm_rg.example", Layer: "/src", Source: "test.yaml"},
		&ImportBlock{To: "azurerm_rg.example", Layer: "/dst", Source: "test.yaml"},
		&ImportBlock{To: "azurerm_vnet.main", Layer: "/dst", Source: "test.yaml"},
	}

	cond := InferConditions(blocks)
	if cond == nil {
		t.Fatal("expected non-nil conditions")
	}

	// RemovedBlock → resources_exist
	if len(cond.ResourcesExist) != 1 {
		t.Fatalf("expected 1 resources_exist check, got %d", len(cond.ResourcesExist))
	}
	if cond.ResourcesExist[0].Layer != "." {
		t.Errorf("resources_exist layer = %q, want %q", cond.ResourcesExist[0].Layer, ".")
	}
	if len(cond.ResourcesExist[0].Addresses) != 1 || cond.ResourcesExist[0].Addresses[0] != "azurerm_rg.example" {
		t.Errorf("resources_exist addresses = %v, want [azurerm_rg.example]", cond.ResourcesExist[0].Addresses)
	}

	// ImportBlocks → resources_not_exist (sorted, deduplicated)
	if len(cond.ResourcesNotExist) != 1 {
		t.Fatalf("expected 1 resources_not_exist check, got %d", len(cond.ResourcesNotExist))
	}
	if cond.ResourcesNotExist[0].Layer != "." {
		t.Errorf("resources_not_exist layer = %q, want %q", cond.ResourcesNotExist[0].Layer, ".")
	}
	wantNotExist := []string{"azurerm_rg.example", "azurerm_vnet.main"}
	if len(cond.ResourcesNotExist[0].Addresses) != len(wantNotExist) {
		t.Fatalf("resources_not_exist addresses = %v, want %v", cond.ResourcesNotExist[0].Addresses, wantNotExist)
	}
	for i, addr := range cond.ResourcesNotExist[0].Addresses {
		if addr != wantNotExist[i] {
			t.Errorf("resources_not_exist[%d] = %q, want %q", i, addr, wantNotExist[i])
		}
	}
}

func TestInferConditionsEmpty(t *testing.T) {
	cond := InferConditions(nil)
	if cond != nil {
		t.Errorf("expected nil for empty blocks, got %+v", cond)
	}
}

func TestInferConditionsImportOnly(t *testing.T) {
	blocks := []Block{
		&ImportBlock{To: "azurerm_rg.example", Layer: "/dst", Source: "test.yaml"},
	}
	cond := InferConditions(blocks)
	if cond == nil {
		t.Fatal("expected non-nil conditions")
	}
	if len(cond.ResourcesExist) != 0 {
		t.Errorf("expected no resources_exist, got %d", len(cond.ResourcesExist))
	}
	if len(cond.ResourcesNotExist) != 1 {
		t.Fatalf("expected 1 resources_not_exist check, got %d", len(cond.ResourcesNotExist))
	}
	if cond.ResourcesNotExist[0].Addresses[0] != "azurerm_rg.example" {
		t.Errorf("got %q", cond.ResourcesNotExist[0].Addresses[0])
	}
}

func TestInferConditionsMovedBlock(t *testing.T) {
	blocks := []Block{
		&MovedBlock{From: "azurerm_vnet.old", To: "azurerm_vnet.new", Layer: "/layer", Source: "test.yaml"},
	}
	cond := InferConditions(blocks)
	if cond == nil {
		t.Fatal("expected non-nil conditions")
	}

	// MovedBlock → resources_exist for From
	if len(cond.ResourcesExist) != 1 {
		t.Fatalf("expected 1 resources_exist, got %d", len(cond.ResourcesExist))
	}
	if cond.ResourcesExist[0].Addresses[0] != "azurerm_vnet.old" {
		t.Errorf("resources_exist addr = %q, want azurerm_vnet.old", cond.ResourcesExist[0].Addresses[0])
	}

	// MovedBlock → resources_not_exist for To
	if len(cond.ResourcesNotExist) != 1 {
		t.Fatalf("expected 1 resources_not_exist, got %d", len(cond.ResourcesNotExist))
	}
	if cond.ResourcesNotExist[0].Addresses[0] != "azurerm_vnet.new" {
		t.Errorf("resources_not_exist addr = %q, want azurerm_vnet.new", cond.ResourcesNotExist[0].Addresses[0])
	}
}

func TestInferConditionsDeduplication(t *testing.T) {
	// Same address from multiple blocks should be deduplicated
	blocks := []Block{
		&RemovedBlock{From: "azurerm_rg.x", Layer: "/layer", Source: "test.yaml"},
		&RemovedBlock{From: "azurerm_rg.x", Layer: "/layer", Source: "test.yaml"},
		&ImportBlock{To: "azurerm_rg.x", Layer: "/layer", Source: "test.yaml"},
		&ImportBlock{To: "azurerm_rg.x", Layer: "/layer", Source: "test.yaml"},
	}
	cond := InferConditions(blocks)
	if cond == nil {
		t.Fatal("expected non-nil")
	}
	if len(cond.ResourcesExist[0].Addresses) != 1 {
		t.Errorf("expected 1 deduplicated address, got %d", len(cond.ResourcesExist[0].Addresses))
	}
	if len(cond.ResourcesNotExist[0].Addresses) != 1 {
		t.Errorf("expected 1 deduplicated address, got %d", len(cond.ResourcesNotExist[0].Addresses))
	}
}

func TestMergeConditions(t *testing.T) {
	a := &MetadataCondition{
		ResourcesExist: []MetadataResourceCheck{
			{Layer: ".", Addresses: []string{"azurerm_rg.a", "azurerm_rg.b"}},
		},
	}
	b := &MetadataCondition{
		ResourcesExist: []MetadataResourceCheck{
			{Layer: ".", Addresses: []string{"azurerm_rg.b", "azurerm_rg.c"}},
		},
		ResourcesNotExist: []MetadataResourceCheck{
			{Layer: ".", Addresses: []string{"azurerm_vnet.x"}},
		},
	}

	result := MergeConditions(a, b)
	if result == nil {
		t.Fatal("expected non-nil")
	}

	// resources_exist should merge and deduplicate: a, b, c
	if len(result.ResourcesExist) != 1 {
		t.Fatalf("expected 1 resources_exist check, got %d", len(result.ResourcesExist))
	}
	wantExist := []string{"azurerm_rg.a", "azurerm_rg.b", "azurerm_rg.c"}
	if len(result.ResourcesExist[0].Addresses) != len(wantExist) {
		t.Fatalf("addresses = %v, want %v", result.ResourcesExist[0].Addresses, wantExist)
	}
	for i, addr := range result.ResourcesExist[0].Addresses {
		if addr != wantExist[i] {
			t.Errorf("addr[%d] = %q, want %q", i, addr, wantExist[i])
		}
	}

	// resources_not_exist from b only
	if len(result.ResourcesNotExist) != 1 {
		t.Fatalf("expected 1 resources_not_exist, got %d", len(result.ResourcesNotExist))
	}
	if result.ResourcesNotExist[0].Addresses[0] != "azurerm_vnet.x" {
		t.Errorf("got %q", result.ResourcesNotExist[0].Addresses[0])
	}
}

func TestMergeConditionsMultiLayer(t *testing.T) {
	a := &MetadataCondition{
		ResourcesExist: []MetadataResourceCheck{
			{Layer: ".", Addresses: []string{"azurerm_rg.local"}},
		},
	}
	b := &MetadataCondition{
		ResourcesExist: []MetadataResourceCheck{
			{Layer: "./other", Addresses: []string{"azurerm_rg.remote"}},
		},
	}

	result := MergeConditions(a, b)
	if result == nil {
		t.Fatal("expected non-nil")
	}
	if len(result.ResourcesExist) != 2 {
		t.Fatalf("expected 2 resources_exist checks (2 layers), got %d", len(result.ResourcesExist))
	}
	// Sorted by layer: "." before "./other"
	if result.ResourcesExist[0].Layer != "." {
		t.Errorf("first check layer = %q", result.ResourcesExist[0].Layer)
	}
	if result.ResourcesExist[1].Layer != "./other" {
		t.Errorf("second check layer = %q", result.ResourcesExist[1].Layer)
	}
}

func TestMergeConditionsOneNil(t *testing.T) {
	cond := &MetadataCondition{
		ResourcesExist: []MetadataResourceCheck{
			{Layer: ".", Addresses: []string{"azurerm_rg.x"}},
		},
	}

	if result := MergeConditions(nil, cond); result != cond {
		t.Error("nil + cond should return cond")
	}
	if result := MergeConditions(cond, nil); result != cond {
		t.Error("cond + nil should return cond")
	}
}

func TestMergeConditionsBothNil(t *testing.T) {
	if result := MergeConditions(nil, nil); result != nil {
		t.Error("nil + nil should return nil")
	}
}

func TestRelativizeCondition_LayerConditions(t *testing.T) {
	cond := &MetadataCondition{
		LayerExists:    []string{"./layers/source", "./layers/compute"},
		LayerNotExists: []string{"./layers/deprecated"},
	}

	// RelativizeCondition should copy LayerExists and LayerNotExists through unchanged
	result := RelativizeCondition(cond, "./layers/compute")

	if result == nil {
		t.Fatal("expected non-nil result")
	}

	// LayerExists should be copied unchanged (not relativized like resource checks)
	if len(result.LayerExists) != 2 {
		t.Fatalf("expected 2 layer_exists entries, got %d", len(result.LayerExists))
	}
	if result.LayerExists[0] != "./layers/source" {
		t.Errorf("expected layer_exists[0] %q, got %q", "./layers/source", result.LayerExists[0])
	}
	if result.LayerExists[1] != "./layers/compute" {
		t.Errorf("expected layer_exists[1] %q, got %q", "./layers/compute", result.LayerExists[1])
	}

	// LayerNotExists should be copied unchanged
	if len(result.LayerNotExists) != 1 {
		t.Fatalf("expected 1 layer_not_exists entry, got %d", len(result.LayerNotExists))
	}
	if result.LayerNotExists[0] != "./layers/deprecated" {
		t.Errorf("expected layer_not_exists[0] %q, got %q", "./layers/deprecated", result.LayerNotExists[0])
	}

	// Verify original was not modified
	if len(cond.LayerExists) != 2 || cond.LayerExists[0] != "./layers/source" {
		t.Error("original condition was modified")
	}
}

func TestMergeConditions_LayerConditions(t *testing.T) {
	a := &MetadataCondition{
		LayerExists:    []string{"./layers/source", "./layers/shared"},
		LayerNotExists: []string{"./layers/deprecated"},
	}
	b := &MetadataCondition{
		LayerExists:    []string{"./layers/shared", "./layers/compute"},
		LayerNotExists: []string{"./layers/deprecated", "./layers/old"},
	}

	result := MergeConditions(a, b)
	if result == nil {
		t.Fatal("expected non-nil result")
	}

	// LayerExists should be deduplicated and sorted: compute, shared, source
	expectedExists := []string{"./layers/compute", "./layers/shared", "./layers/source"}
	if len(result.LayerExists) != len(expectedExists) {
		t.Fatalf("expected %d layer_exists entries, got %d: %v", len(expectedExists), len(result.LayerExists), result.LayerExists)
	}
	for i, path := range result.LayerExists {
		if path != expectedExists[i] {
			t.Errorf("layer_exists[%d] = %q, want %q", i, path, expectedExists[i])
		}
	}

	// LayerNotExists should be deduplicated and sorted: deprecated, old
	expectedNotExists := []string{"./layers/deprecated", "./layers/old"}
	if len(result.LayerNotExists) != len(expectedNotExists) {
		t.Fatalf("expected %d layer_not_exists entries, got %d: %v", len(expectedNotExists), len(result.LayerNotExists), result.LayerNotExists)
	}
	for i, path := range result.LayerNotExists {
		if path != expectedNotExists[i] {
			t.Errorf("layer_not_exists[%d] = %q, want %q", i, path, expectedNotExists[i])
		}
	}
}

func TestRenderAndParseMetadata_VersionAndSourceLayer(t *testing.T) {
	meta := &MigrationMetadata{
		Version: CurrentMetadataVersion,
		SourceLayer: &MetadataSourceLayer{
			StorageAccountName: "acct",
			ContainerName:      "tfstate",
			Key:                "layers/compute.tfstate",
		},
		Resources: []string{"azurerm_resource_group.rg"},
	}

	rendered := RenderMetadataComment(meta)
	if !strings.Contains(rendered, `"version":2`) {
		t.Errorf("expected version in rendered metadata, got:\n%s", rendered)
	}
	if !strings.Contains(rendered, `"source_layer"`) {
		t.Errorf("expected source_layer in rendered metadata, got:\n%s", rendered)
	}

	parsed, err := ParseMetadataComment(rendered)
	if err != nil {
		t.Fatalf("ParseMetadataComment error: %v", err)
	}
	if parsed.Version != CurrentMetadataVersion {
		t.Errorf("version = %d, want %d", parsed.Version, CurrentMetadataVersion)
	}
	if parsed.SourceLayer == nil {
		t.Fatal("source_layer nil after round-trip")
	}
	if parsed.SourceLayer.StorageAccountName != "acct" ||
		parsed.SourceLayer.ContainerName != "tfstate" ||
		parsed.SourceLayer.Key != "layers/compute.tfstate" {
		t.Errorf("source_layer round-trip mismatch: %+v", parsed.SourceLayer)
	}
}

// TestParseMetadata_LegacyFileNoVersionOrSourceLayer confirms backward
// compatibility: a v1 file (no version, no source_layer) parses with the zero
// value for the new fields, so it is treated as unscoped everywhere.
func TestParseMetadata_LegacyFileNoVersionOrSourceLayer(t *testing.T) {
	content := `# Generated by statebridge - do not edit manually
#
# statebridge:metadata:begin
# {"conditions":{"resources_exist":[{"layer":".","addresses":["aws_instance.web"]}]},"resources":["aws_instance.web"]}
# statebridge:metadata:end

removed {
  from = aws_instance.web
}
`
	meta, err := ParseMetadataComment(content)
	if err != nil {
		t.Fatalf("ParseMetadataComment error: %v", err)
	}
	if meta == nil {
		t.Fatal("expected metadata, got nil")
	}
	if meta.Version != 0 {
		t.Errorf("legacy version = %d, want 0", meta.Version)
	}
	if meta.SourceLayer != nil {
		t.Errorf("legacy source_layer = %+v, want nil", meta.SourceLayer)
	}
}

func TestMetadataSourceLayer_Matches(t *testing.T) {
	tests := []struct {
		name             string
		descriptor       *MetadataSourceLayer
		account          string
		container        string
		key              string
		wantMatch        bool
		wantDeterminable bool
	}{
		{
			name:       "nil descriptor matches everything",
			descriptor: nil,
			account:    "a", container: "c", key: "k",
			wantMatch: true, wantDeterminable: true,
		},
		{
			name:       "full triple exact match",
			descriptor: &MetadataSourceLayer{StorageAccountName: "a", ContainerName: "c", Key: "k1"},
			account:    "a", container: "c", key: "k1",
			wantMatch: true, wantDeterminable: true,
		},
		{
			name:       "different key is determinable mismatch",
			descriptor: &MetadataSourceLayer{StorageAccountName: "a", ContainerName: "c", Key: "k1"},
			account:    "a", container: "c", key: "k2",
			wantMatch: false, wantDeterminable: true,
		},
		{
			name:       "keyed descriptor but caller has no key is indeterminate",
			descriptor: &MetadataSourceLayer{StorageAccountName: "a", ContainerName: "c", Key: "k1"},
			account:    "a", container: "c", key: "",
			wantMatch: false, wantDeterminable: false,
		},
		{
			name:       "empty descriptor fields act as wildcards",
			descriptor: &MetadataSourceLayer{Key: "k1"},
			account:    "any", container: "any", key: "k1",
			wantMatch: true, wantDeterminable: true,
		},
		{
			name:       "account mismatch",
			descriptor: &MetadataSourceLayer{StorageAccountName: "a", ContainerName: "c"},
			account:    "b", container: "c", key: "",
			wantMatch: false, wantDeterminable: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			match, determinable := tt.descriptor.Matches(tt.account, tt.container, tt.key)
			if match != tt.wantMatch {
				t.Errorf("match = %v, want %v", match, tt.wantMatch)
			}
			if determinable != tt.wantDeterminable {
				t.Errorf("determinable = %v, want %v", determinable, tt.wantDeterminable)
			}
		})
	}
}

func TestMetadataSourceLayer_OwnedByOther(t *testing.T) {
	tests := []struct {
		name       string
		descriptor *MetadataSourceLayer
		account    string
		container  string
		key        string
		want       bool
	}{
		{"nil is never owned by other", nil, "a", "c", "k", false},
		{"exact match not owned by other", &MetadataSourceLayer{StorageAccountName: "a", ContainerName: "c", Key: "k1"}, "a", "c", "k1", false},
		{"determinable mismatch is owned by other", &MetadataSourceLayer{StorageAccountName: "a", ContainerName: "c", Key: "k1"}, "a", "c", "k2", true},
		{"indeterminate is not owned by other", &MetadataSourceLayer{StorageAccountName: "a", ContainerName: "c", Key: "k1"}, "a", "c", "", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.descriptor.OwnedByOther(tt.account, tt.container, tt.key); got != tt.want {
				t.Errorf("OwnedByOther = %v, want %v", got, tt.want)
			}
		})
	}
}
