package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const defaultMigrationFilename = "migrations.tf"

// Writer collects HCL blocks and writes them grouped by layer directory.
type Writer struct {
	blocks []Block

	// DryRun controls whether files are actually written to disk.
	// When true, content is generated but not written.
	DryRun bool

	// OutputFilename overrides the default output filename within each layer dir.
	// Defaults to "migrations.tf".
	OutputFilename string
}

// NewWriter creates a Writer with default settings.
func NewWriter() *Writer {
	return &Writer{
		OutputFilename: defaultMigrationFilename,
	}
}

// AddBlock adds a single block to the writer's collection.
func (w *Writer) AddBlock(b Block) {
	w.blocks = append(w.blocks, b)
}

// AddBlocks adds multiple blocks at once.
func (w *Writer) AddBlocks(blocks []Block) {
	w.blocks = append(w.blocks, blocks...)
}

// GroupedByLayer returns blocks grouped by their target layer path.
// The order of blocks within each group is preserved.
func (w *Writer) GroupedByLayer() map[string][]Block {
	grouped := make(map[string][]Block)
	for _, b := range w.blocks {
		layer := b.LayerPath()
		grouped[layer] = append(grouped[layer], b)
	}
	return grouped
}

// RenderLayer generates the full HCL content for all blocks targeting a given layer.
func (w *Writer) RenderLayer(layerPath string) string {
	grouped := w.GroupedByLayer()
	blocks, ok := grouped[layerPath]
	if !ok {
		return ""
	}
	return renderBlocks(blocks)
}

// RenderAll generates the full HCL content for all layers, returned as a map
// of layer path to rendered HCL content.
func (w *Writer) RenderAll() map[string]string {
	result := make(map[string]string)
	for layer, blocks := range w.GroupedByLayer() {
		result[layer] = renderBlocks(blocks)
	}
	return result
}

// WriteAll writes all collected blocks to their respective layer directories.
// Each layer gets a single file containing all its blocks.
// Returns the list of file paths written and any error encountered.
func (w *Writer) WriteAll() ([]string, error) {
	var written []string

	for layer, content := range w.RenderAll() {
		outPath := filepath.Join(layer, w.outputFilename())

		if w.DryRun {
			written = append(written, outPath)
			continue
		}

		if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
			return written, fmt.Errorf("writing migration file %q: %w", outPath, err)
		}
		written = append(written, outPath)
	}

	return written, nil
}

// outputFilename returns the effective output filename.
func (w *Writer) outputFilename() string {
	if w.OutputFilename != "" {
		return w.OutputFilename
	}
	return defaultMigrationFilename
}

// renderBlocks generates HCL content from a list of blocks, including a header
// and optional per-block comments.
func renderBlocks(blocks []Block) string {
	var sb strings.Builder

	sb.WriteString("# Generated by tfmigrate - do not edit manually\n")

	for i, b := range blocks {
		if i > 0 || true {
			sb.WriteString("\n")
		}
		if comment := b.Comment(); comment != "" {
			sb.WriteString(fmt.Sprintf("# %s\n", comment))
		}
		sb.WriteString(b.Render())
		sb.WriteString("\n")
	}

	return sb.String()
}
