package tofu

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/terraprovider/statebridge/pkg/generator"
)

func writeMigrationFile(t *testing.T, dir, filename, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, filename), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestScanMigrationTargets_SingleFile(t *testing.T) {
	dir := t.TempDir()

	meta := &generator.MigrationMetadata{
		Resources: []string{"aws_instance.web", "aws_s3_bucket.data"},
	}
	content := "# Generated by statebridge - do not edit manually\n" +
		generator.RenderMetadataComment(meta) +
		"\nimport {\n  to = aws_instance.web\n  id = \"i-123\"\n}\n"

	writeMigrationFile(t, dir, "migration.001_move.a1b2c3d4.tf", content)

	addrs, err := ScanMigrationTargets(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(addrs) != 2 {
		t.Fatalf("expected 2 addresses, got %d: %v", len(addrs), addrs)
	}
	if addrs[0] != "aws_instance.web" {
		t.Errorf("expected aws_instance.web first (sorted), got %q", addrs[0])
	}
	if addrs[1] != "aws_s3_bucket.data" {
		t.Errorf("expected aws_s3_bucket.data second, got %q", addrs[1])
	}
}

func TestScanMigrationTargets_MultipleFiles(t *testing.T) {
	dir := t.TempDir()

	meta1 := &generator.MigrationMetadata{
		Resources: []string{"aws_instance.web", "aws_s3_bucket.data"},
	}
	content1 := "# Generated\n" + generator.RenderMetadataComment(meta1) + "\n"
	writeMigrationFile(t, dir, "migration.001_move.aaaa0000.tf", content1)

	meta2 := &generator.MigrationMetadata{
		Resources: []string{"aws_s3_bucket.data", "aws_vpc.main"},
	}
	content2 := "# Generated\n" + generator.RenderMetadataComment(meta2) + "\n"
	writeMigrationFile(t, dir, "migration.002_rename.bbbb1111.tf", content2)

	addrs, err := ScanMigrationTargets(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	// Deduplicated and sorted: aws_instance.web, aws_s3_bucket.data, aws_vpc.main
	if len(addrs) != 3 {
		t.Fatalf("expected 3 deduplicated addresses, got %d: %v", len(addrs), addrs)
	}
	expected := []string{"aws_instance.web", "aws_s3_bucket.data", "aws_vpc.main"}
	for i, exp := range expected {
		if addrs[i] != exp {
			t.Errorf("addrs[%d] = %q, want %q", i, addrs[i], exp)
		}
	}
}

func TestScanMigrationTargets_NoMigrationFiles(t *testing.T) {
	dir := t.TempDir()

	addrs, err := ScanMigrationTargets(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(addrs) != 0 {
		t.Errorf("expected 0 addresses for empty directory, got %d", len(addrs))
	}
}

func TestScanMigrationTargets_NoMetadata(t *testing.T) {
	dir := t.TempDir()

	// File matches glob pattern but has no metadata comment
	writeMigrationFile(t, dir, "migration.001_move.abcd1234.tf", `
import {
  to = aws_instance.web
  id = "i-123"
}
`)

	addrs, err := ScanMigrationTargets(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(addrs) != 0 {
		t.Errorf("expected 0 addresses (no metadata), got %d: %v", len(addrs), addrs)
	}
}

func TestScanMigrationTargets_NonMigrationFilesIgnored(t *testing.T) {
	dir := t.TempDir()

	// Non-migration .tf file should be ignored
	writeMigrationFile(t, dir, "main.tf", "resource \"aws_instance\" \"web\" {}")

	meta := &generator.MigrationMetadata{
		Resources: []string{"aws_vpc.main"},
	}
	content := "# Generated\n" + generator.RenderMetadataComment(meta) + "\n"
	writeMigrationFile(t, dir, "migration.001_net.cccc2222.tf", content)

	addrs, err := ScanMigrationTargets(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(addrs) != 1 {
		t.Fatalf("expected 1 address, got %d: %v", len(addrs), addrs)
	}
	if addrs[0] != "aws_vpc.main" {
		t.Errorf("expected aws_vpc.main, got %q", addrs[0])
	}
}

func TestScanMigrationTargets_WithConditions(t *testing.T) {
	dir := t.TempDir()

	meta := &generator.MigrationMetadata{
		Conditions: &generator.MetadataCondition{
			ResourcesExist: []generator.MetadataResourceCheck{
				{Layer: ".", Addresses: []string{"aws_instance.web"}},
			},
		},
		Resources: []string{"aws_instance.web"},
	}
	content := "# Generated\n" + generator.RenderMetadataComment(meta) + "\n"
	writeMigrationFile(t, dir, "migration.001_move.dddd3333.tf", content)

	addrs, err := ScanMigrationTargets(dir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(addrs) != 1 {
		t.Fatalf("expected 1 address, got %d", len(addrs))
	}
	if addrs[0] != "aws_instance.web" {
		t.Errorf("expected aws_instance.web, got %q", addrs[0])
	}
}
