name: E2E Fast Tests

on:
  pull_request:
    branches: [main]
    paths:
      - 'e2e/**'
      - 'pkg/**'
      - 'cmd/**'
      - 'go.mod'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: read
  checks: write
  pull-requests: write

env:
  ARM_USE_OIDC: "true"
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  E2E_STORAGE_ACCOUNT_NAME: ${{ vars.E2E_STORAGE_ACCOUNT_NAME }}

jobs:
  e2e_fast:
    runs-on: ubuntu-latest-8cpu

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-go-test
        with:
          setup-tofu: "true"
          test-args: -tags=e2e_fast -timeout=10m -count=1 ./e2e/...
          gotestsum-format: standard-verbose
          check-name: E2E Fast Test Results
