name: Lint

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest-8cpu
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: ./.github/actions/setup-go-lint
