name: Lint

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest-8cpu
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup-go-lint
