name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest-8cpu
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}

    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.55.1
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - name: Install tools
        run: aqua install

      - name: Run GoReleaser
        run: goreleaser release --clean --skip publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: dist
          path: |
            dist/*.sbom.json
            dist/*.sigstore.json
            dist/*.tar.gz
            dist/*.zip
            dist/*.txt

      - name: Generate hashes
        id: hash
        run: |
          # sha256sum generates sha256 hash for all artifacts.
          # base64 -w0 encodes to base64 and outputs on a single line.
          # sha256sum artifact1 artifact2 ... | base64 -w0
          echo "hashes=$(find dist \( -name "*.tar.gz" -o -name "*.zip" \) -print0 | xargs -0 -r sha256sum | base64 -w0)" >> "$GITHUB_OUTPUT"

  attestation:
    timeout-minutes: 10
    runs-on: ubuntu-latest-8cpu
    needs: [build]
    permissions:
      id-token: write # required for GitHub Artifact Attestations
      attestations: write # required for GitHub Artifact Attestations
      artifact-metadata: write # required for GitHub Artifact Attestations
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: dist
          path: dist
      - uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: |
            dist/*.sbom.json
            dist/*.sigstore.json
            dist/*.tar.gz
            dist/*.zip
            dist/*.txt

  provenance:
    needs: [build]
    permissions:
      actions: read # Needed for detection of GitHub Actions environment.
      id-token: write # Needed for provenance signing and ID
      contents: write # Needed for release uploads
    # slsa-framework/slsa-github-generator doesn't support pinning version
    # > Invalid ref: 68bad40844440577b33778c9f29077a3388838e9. Expected ref of the form refs/tags/vX.Y.Z
    # https://github.com/slsa-framework/slsa-github-generator/issues/722
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      upload-assets: false

  release:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    needs: [build, provenance]
    permissions:
      contents: write # required to create a release
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: dist
          path: dist
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: ${{ needs.provenance.outputs.provenance-name }}
          path: dist

      - run: ls dist
      - run: gh release create -R "$GITHUB_REPOSITORY" "$GITHUB_REF_NAME" -p dist/*
        env:
          GITHUB_TOKEN: ${{ github.token }}
