name: Test

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest-8cpu
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: ./.github/actions/setup-go-test
        with:
          check-name: Unit Test Results

      - run: go vet ./...

      - run: go build ./...
