name: Test

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest-8cpu
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup-go-test
        with:
          check-name: Unit Test Results

      - run: go vet ./...

      - run: go build ./...
