name: Vulnerability Check

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 8 * * 1" # every Monday at 08:00 UTC

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-go-vulncheck
