name: Vulnerability Check

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 8 * * 1" # every Monday at 08:00 UTC

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup-go-vulncheck
